# Generated by Django 2.2.4 on 2020-01-27 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evento',
            old_name='Categoria',
            new_name='categoria',
        ),
    ]
