# Generated by Django 2.2.4 on 2020-01-27 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200126_1953'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evento',
            old_name='Presencial',
            new_name='presencial',
        ),
    ]
